- name: install docker-compose
  pacman:
    name: docker-compose
    update_cache: true
  become: true

- name: getting docker info
  command: docker info --format '{{ "{{" }} json . {{ "}}" }}'
  register: docker_info
  become: true

# this solves issues where the graph driver gets unresponsive
- block:
    - name: listing graph root content
      find:
        paths: "{{ docker_info.stdout | from_json | json_query('DockerRootDir') }}/zfs/graph/"
        file_type: directory
      register: graph_driver_dirs

    - name: find mounted graph driver dirs
      command: findmnt -f -J {{ item.path }}
      register: findmnt
      ignore_errors: true
      with_items: "{{ graph_driver_dirs.files }}"

    - name: cleaning docker graph driver on zfs
      shell: rmdir {{ item.0.path }}
      when: item.1|failed
      with_together:
        - "{{ graph_driver_dirs.files }}"
        - "{{ findmnt.results }}"

  when: docker_info.stdout | from_json | json_query('Driver') == 'zfs'
  become: true


- block:
    - name: create temporary build directory
      tempfile:
        state: directory
      register: tempdir
      become: true

    - name: templating compose file
      template:
        src: "{{ docker_compose_file_path }}"
        dest: "{{ tempdir.path }}/docker-compose.yml"
      become: true

    - name: pulling docker images
      command: "docker-compose -p {{ docker_compose_project }} -f {{ tempdir.path }}/docker-compose.yml pull"
      when: docker_compose_pull
      become: true

    - name: "docker compose up"
      command: "docker-compose -p {{ docker_compose_project }} -f {{ tempdir.path }}/docker-compose.yml up -d"
      become: true

  always:
    - name: removing docker-compose.yml
      file:
        path: "{{ tempdir }}"
        state: absent
      become: true
